enum DataSourceFilterOperation {
    LT
    LTE
    EQ
    GTE
    GT
    CONTAINS
}

input DataSourceOrderInput {
    field: String!
    desc: Boolean!
}

input DataSourceFilterInput {
    field: String!
    op: DataSourceFilterOperation!
    value: String!
}

type DataSourcePageInfo {
    hasNextPage: Boolean
    hasPreviousPage: Boolean
}
